#cloud-config
users:
  - default
  - name: ubuntu
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCmiz5cpmucrR8qYq2MXHaJYo1P48DufGdp3d2RFhl/DSe2ocYVIAQoREYqPHAxSegXHgnYycnzrDDUjeJPj6+ZryhQCRS00J9qIaxkbN3skO7FZD1hIV4tCkNuJd7eRoBcnzibXf5jhCRlQcrXq0IxLVqYv3nZ/MvCGhuYHqnSBvsQ0U6qIXcm5HxyfG0CDYfZpn/GeNQQsru24q1e7+wC5AE7R8P/c2GRfZkehXgrr5c14Zz18w8MboC4eFcNw7u2WsD2XwI9za8M9bxmUqkokgvWq3O14P88j/gQ9LsCdRsQVa1BUcOInuInfIs5+YogAvWZ34EtogSHCuODrbuMhAY/CZV3gXjio2g8tous6euvTmK2nppOM93K/fcvBEf6G045yRisJyLyPlYLojKBKke3Rkc1xDPj907qlWAiTHoG4ub71G05iIds2qqKUbqE5IfHjhRrSobmegBi/ibtY6oFmBbevwaG2vCnxizRPhp92vtgQB5oqaSpZ9lckRU= matias@matias-TP
